name: Django project deploy

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASS: ${{ secrets.DB_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.DB_HOST }}
      POSTGRES_PORT: ${{ secrets.DB_PORT }}
      POSTGRES_DB: ${{ secrets.DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
    services:
      postgres_service:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASS }}
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check changes in repo
        uses: actions/checkout@v2

      - name: Python installation
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install requirements
        run:
          pip install -r requirements.txt

      - name: Code linting
        run: flake8 logistic/models.py

      - name: Test using pytest
        run: pytest
        env:
          SECRET_KEY: ${{ env.SECRET_KEY }}
          DEBUG: "0"
          ALLOWED_HOSTS: ${{ env.ALLOWED_HOSTS }}
          DB_NAME: ${{ env.POSTGRES_DB }}
          DB_USER: ${{ env.POSTGRES_USER }}
          DB_PASSWORD: ${{ env.POSTGRES_PASS }}
          DB_HOST: ${{ env.POSTGRES_HOST }}
          DB_PORT: ${{ env.POSTGRES_PORT }}
  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: deploy process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            su - user
            cd /home/user/project/
            git pull
            systemctl restart gunicorn
            
